Brandon
DoctorEpsilon/Personal-diary-React pull request #1
Opened 2020-09-21 13:58 UTC by Brandon-MK

The **Personal Diary Website** created using React

2020-09-21 14:00 UTC, heisfullstacked commented
Change the PR title. Add description mentioning what you did.

2020-09-21 14:03 UTC, heisfullstacked requested changes

2020-09-21 14:03 UTC, heisfullstacked commented on README.md
> +# Personal-diary-React
Add some instructions about how to setup the repo, install the dependencies and run the webapp.

2020-09-21 14:03 UTC, heisfullstacked commented on package.json
> +  "private": true,
false

2020-09-21 15:17 UTC, Brandon-MK commented
@heisfullstacked i have made the changes you told me to do!

2020-09-22 17:58 UTC, heisfullstacked approved these changes

2020-09-22 17:59 UTC, merged